version: '3.5'

services:
  server:
    build:
      context: ./server
      dockerfile: "Dockerfile"
    hostname: paradiseserver
    ports:
      - 8080:8080

  client:
    build:
      context: ./client
      dockerfile: "Dockerfile"
    hostname: paradiseclient
    ports:
      - 5173:5173
